Better gaslight
MiataBoy/Paw pull request #11
Opened 2023-06-13 22:49 UTC by Soapy7261

This uses a function for gaslight so we can have it know what emojis are on the server and have things generally look nicer

2023-06-13 22:51 UTC, Soapy7261 commented
And yes toothy, the code works on my other bot and tbh there's not much room for error

2023-06-14 15:37 UTC, ToothyDev commented on cogs/socials.py
> +        gpthistory = [{"role": "system", "content": f"{get_gaslight(ctx.guild.emojis, ctx.author.display_name)}"}]
I doubt the code works on your machine because you never await the async get_gaslight function.

2023-06-14 15:37 UTC, ToothyDev requested changes
Fix the commented issue

2023-06-14 17:19 UTC, MiataBoy commented
I do not review PRs regarding the GPT function. Please stick to requesting review from @ToothyDev from now on.
Thanks in advance.

2023-06-14 19:18 UTC, Soapy7261 commented
It auto requested you

2023-06-14 21:06 UTC, ToothyDev approved these changes

2023-06-14 21:06 UTC, merged